feat: one dockerfile
Co-authored-by: Copilot <copilot@github.com>

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,14 +1,42 @@
-#
-# Container Creation for the F110 race-stack at Center for Project Based Learning, ETH
-#
-ARG BASE_IMAGE=base_x86
-FROM race_stack:${BASE_IMAGE}
-
-# initial user setup
+ARG IMAGE=ros:humble-robot
+FROM ${IMAGE}
+ARG PLATFORM=arm
 ARG USER
 ARG UID
 ARG GID
 
+RUN if [[ "$(uname -m)" == "aarch64" ]] && [[ "$PLATFORM" == "jet" ]]; then \
+    echo "Building for Jetson ARM architecture..."; \
+    if [[ "$IMAGE" != "dustynv/ros:humble-ros-base-l4t-r36.3.0" ]]; then \
+    echo "Error: The selected base image is wrong."; \
+    exit 1; \
+    fi; \
+    elif [[ "$(uname -m)" == "arm64" ]] && [[ "$PLATFORM" == "arm" ]]; then \
+    echo "Building for Apple ARM architecture..."; \
+    if [[ "$IMAGE" != "ros:humble-ros-base" ]]; then \
+    echo "Error: The selected base image is wrong."; \
+    exit 1; \
+    fi; \
+    elif [[ "$(uname -m)" == "x86_64" ]] && [[ "$PLATFORM" == "x86" ]]; then \
+    echo "Building for x86 architecture..."; \
+    if [[ "$IMAGE" != "ros:humble-ros-base" ]]; then \
+    echo "Error: The selected base image is wrong."; \
+    exit 1; \
+    fi; \
+    fi;
+
+
+
+SHELL [ "/bin/bash", "-c" ]
+ARG DEBIAN_FRONTEND=noninteractive
+
+ADD ./.install_utils/linux_req/linux_req.txt /.install_utils/linux_req.txt
+RUN apt-get update && xargs apt-get install -y < /.install_utils/linux_req.txt
+ADD ./.install_utils/python_req.txt /tmp/.install_utils/python_req.txt
+RUN pip3 install -r /tmp/.install_utils/python_req.txt &&\
+    pip3 install quadprog~=0.1.11
+
+ADD ./.install_utils /.install_utils
 RUN useradd -ms /bin/bash -u ${UID} -G sudo ${USER} && groupadd -fg ${GID} ${USER} \
     && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
 USER $USER
